### ISSUE TITLE
errore: il modello non può essere caricato

### ISSUE THREAD

**Issue by snuffer82** [ludovico85/Home-range-analysis-through-Kernel-Density-Estimation-in-QGIS#1]
Buonasera,
come da oggetto, se provo a caricare il modello su qgis 3.4, il caricamento fallisce con l'errore riportato in allegato.
Mi potreste dare qualche indicazione su come potrei risolvere il problema?
grazie mille

![versione](https://user-images.githubusercontent.com/17122286/73088177-010f7300-3ed4-11ea-8631-145775341de9.PNG)
![errore](https://user-images.githubusercontent.com/17122286/73088178-010f7300-3ed4-11ea-9c6b-5b79e99e3db1.PNG)

**Comment by ludovico85** [comment]
Salve, probabilmente è un problema dell'installazione di QGIS. Provi ad aggiornare alla versione 3.10 che è l'attuale LTR.
Ho testato sia con 3.4 che con 3.10 e il modello funziona correttamente.

**Comment by snuffer82** [comment]
grazie
